### ISSUE TITLE
NPM module is not linked to this GitHub repository

### ISSUE THREAD

**Issue by almereyda** [andruschka/parcel-plugin-riot#1]
Eventually because it is not mentionned in https://github.com/andruschka/parcel-plugin-riot/blob/master/package.json?

**Comment by andruschka** [comment]
Hi,
I think I don't get what you mean? :-/

**Comment by millette** [comment]
It was fixed with https://github.com/andruschka/parcel-plugin-riot/commit/5e763eb2c3f8b2a440e0e618214f32c0dc9e34ff
